# Jekyll Configuration

url: http://seancronin.org #XXX
title: Sean Cronin #XXX
description: Tag line #XXX
author: Sean Cronin #XXX
email: seancron@gmail.com #XXX
analytics_id: UA-16446358-1 #Google Analytics ID : UA-xxx-xxx  

auto: false
lsi: true
pygments: true
server_port: 4000
markdown: maruku
permalink: /blog/:title

maruku:
  use_tex: false
  use_divs: false
  png_dir: img/tex
  png_url: /img/tex
